### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by phcerdan** [hpc-carpentry/hpc-python#25]
![image](https://user-images.githubusercontent.com/3021667/83857203-ed460a00-a71a-11ea-9e90-a01ed859de5e.png)

That link points to:
https://github.com/hpc-carpentry/hpc-python/blob/gh-pages/hpc-carpentry.github.io/hpc-novice

Which results in 404 error.

**Comment by tkphd** [comment]
... also, it links to a different lesson. Thanks for pointing this out, @phcerdan!

**Comment by tkphd** [comment]
Closed by #26.
